[theme]
primaryColor = "#2ca02c"
backgroundColor = "#FAF8F4"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
font = "sans serif"

[server]
headless = true
enableCORS = true
enableXsrfProtection = true
